Feature/#33 cart
Mini-Team-6/Mini-Team-6-Backend pull request #46
Opened 2023-11-24 03:02 UTC by ypd06021

## 변경사항

변경사항에 대해 간략하게 설명해주세요.
SemVer 규칙을 따라야 합니다

### Issue Link - #1

-----

## 체크리스트

리뷰 요청 전에 확인해야 할 사항들을 나열해주세요.

- [ ] 내 코드를 스스로 검토했나요?
- [ ] 핵심 기능에 대해 충분한 테스트를 수행했나요?
- [ ] 분석이 필요한가요?
- [ ] 이것이 제품 업데이트의 일부인가요? 그렇다면, 이 업데이트에 대해 한 문장으로 작성해주세요.

-----

## 참고
https://semver.org/lang/ko/

2023-11-24 17:23 UTC, laigasus requested changes
수고하셨습니다!

검토 필요한 부분은 댓글로 작성했습니다
Approve 대신 Request Changes로 남길께여

Mockito는 이제 같이 공부하면 될 것 같습니다!

2023-11-24 17:23 UTC, laigasus commented on src/main/java/ybe/mini/travelserver/domain/cart/controller/CartControllerMock.java
> +public class CartControllerMock {
프론트 분들 테스트 해보시라고 작성하신 파일 같아요
`Mock` 이라는 단어를 쓰신 것 같은데
키워드로 `테스트 더블의 종류` 이것에 대해 알아보시면 도움이 될 것 같습니다!

2023-11-24 17:23 UTC, laigasus commented on src/main/java/ybe/mini/travelserver/domain/cart/dto/request/CartCreateRequest.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm")
`@NotBlank` 는 Controller 단 유효성 검사 `@Valid` 를 통해 이루어지는 어노테이션입니다. 체크인, 체크아웃 값이 있어야 결제 완료시 저 기간은 예약에 제한을 두어야 할테니까용. 

@JsonFormat 을 적용하면 저걸 안써도 되는지 확인할 필요가 있군요

2023-11-24 17:23 UTC, laigasus commented on src/main/java/ybe/mini/travelserver/domain/cart/dto/request/CartCreateRequest.java
>      int guestNumber
위 roomId 에서는 Wrapper 클래스를, 여기는 원시 자료유형을 쓰셨네용.

다른 이유가 있을까여?

2023-11-24 17:23 UTC, laigasus commented on src/main/java/ybe/mini/travelserver/domain/cart/dto/response/CartGetResponse.java
> +    public static CartGetResponse fromEntity(Cart cart, Room room, Accommodation accommodation) {
위의 record 매개변수가 여러개일때 한줄로 표현하셨는데, 
여기는 일렬로 되어 있네용

컨벤션에서 합의를 봐야겠습니다

2023-11-24 17:23 UTC, laigasus commented on src/main/java/ybe/mini/travelserver/domain/cart/entity/Cart.java
> +
앗!!!!!!

2023-11-24 17:23 UTC, laigasus commented on src/main/java/ybe/mini/travelserver/domain/cart/controller/CartControllerTemp.java
다음에는 들여쓰기 준수해주세욧!

2023-11-24 17:23 UTC, laigasus commented on src/test/java/ybe/mini/travelserver/domain/cart/service/CartServiceTest.java
단위테스트 Mockito를 함께 공부할 때가 되었군요 😊

2023-11-25 02:36 UTC, ypd06021 commented on src/main/java/ybe/mini/travelserver/domain/cart/controller/CartControllerMock.java
> +public class CartControllerMock {
Dummy 가 좀 더 맞는 네이밍이겠네요!

2023-11-25 02:38 UTC, ypd06021 commented on src/main/java/ybe/mini/travelserver/domain/cart/dto/request/CartCreateRequest.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm")
@JsonFormat으로 유효성 검증할 수 없어서 @NotBlank 추가했습니다

2023-11-25 02:38 UTC, ypd06021 commented on src/main/java/ybe/mini/travelserver/domain/cart/dto/request/CartCreateRequest.java
>      int guestNumber
헤헤 ... integer로 수정했습니다

2023-11-25 02:41 UTC, ypd06021 commented on src/main/java/ybe/mini/travelserver/domain/cart/dto/response/CartGetResponse.java
> +    public static CartGetResponse fromEntity(Cart cart, Room room, Accommodation accommodation) {
매개변수가 길어질 수 있으니 한 줄로 변경하였습니다

2023-11-25 04:10 UTC, yuhyun1 approved these changes
👍

2023-11-25 04:13 UTC, merged